spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mybatis_summarize?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: root123
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      test-on-return: false
      test-while-idle: true
      test-on-borrow: false
      validation-query: SELECT 1


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置懒加载优先级  fetchType="lazy" > lazy-loading-enabled
    lazy-loading-enabled: false  #开启懒加载
    aggressive-lazy-loading: false #开启时，任一方法的调用都会加载该对象的所有延迟加载属性。 否则，每个延迟加载属性会按需加载（参考 lazyLoadTriggerMethods)。	true | false	false （在 3.4.1 及之前的版本中默认为 true）
  mapper-locations: classpath:mapper/*.xml
